import os
from typing import Optional


def _first_env(*names: str) -> Optional[str]:
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return None


DEFAULT_WEBHOOK_URL = _first_env("DISCORD_WEBHOOK_URL")
BET_ALERTS_WEBHOOK_URL = _first_env("DISCORD_BET_ALERTS_WEBHOOK_URL", "DISCORD_WEBHOOK_URL")
LIVE_HAMMER_WEBHOOK_URL = _first_env("DISCORD_LIVE_HAMMER_WEBHOOK_URL", "DISCORD_BET_ALERTS_WEBHOOK_URL", "DISCORD_WEBHOOK_URL")
WATCHLIST_WEBHOOK_URL = _first_env(
    "DISCORD_WATCHLIST_WEBHOOK_URL",
    "DISCORD_STATUS_WEBHOOK_URL",
    "DISCORD_BET_ALERTS_WEBHOOK_URL",
    "DISCORD_WEBHOOK_URL",
)
ARBITRAGE_WEBHOOK_URL = _first_env("DISCORD_ARBITRAGE_WEBHOOK_URL", "DISCORD_BET_ALERTS_WEBHOOK_URL", "DISCORD_WEBHOOK_URL")
STATUS_WEBHOOK_URL = _first_env("DISCORD_STATUS_WEBHOOK_URL", "DISCORD_WEBHOOK_URL")
RESULTS_WEBHOOK_URL = _first_env(
    "DISCORD_RESULTS_WEBHOOK_URL",
    "DISCORD_DAILY_SLIPS_WEBHOOK_URL",
    "DISCORD_STATUS_WEBHOOK_URL",
    "DISCORD_WEBHOOK_URL",
)
DAILY_SLIPS_WEBHOOK_URL = _first_env("DISCORD_DAILY_SLIPS_WEBHOOK_URL", "DISCORD_RESULTS_WEBHOOK_URL", "DISCORD_STATUS_WEBHOOK_URL", "DISCORD_WEBHOOK_URL")
